site_name: Soliplex
site_url: https://soliplex.github.io/soliplex/
dev_addr: 127.0.0.1:8001
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/lightbulb-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  icon:
    repo: fontawesome/brands/github-alt
  # logo: img/icon-white.svg
  # favicon: img/favicon.png
  language: en
repo_name: soliplex/soliplex
repo_url: https://github.com/soliplex/soliplex
plugins:
  # Material for MkDocs
  search:
nav:
  - Home: index.md
  - Overview: overview.md
  - Setup:
      - Server: server.md  
      - Client: client.md
  - Configuration:
      - Filesytem Layout: config/filesystem_layout.md
      - Installation: config/installation.md
      - Rooms: config/rooms.md
      - Completions: config/completions.md
      - Quizzes: config/quizzes.md
      - OIDC Authentication: config/oidc_providers.md
  - Usage: usage.md
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
