services:
  # Production web server
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped

  # Development environment with hot reload
  dev:
    image: ghcr.io/cirruslabs/flutter:3.37.0-0.1.pre
    working_dir: /app
    volumes:
      - ..:/app
    ports:
      - "8081:8080"
    command: flutter run -d web-server --web-hostname=0.0.0.0 --web-port=8080
    profiles:
      - dev
