services:
  # Production web server
  web:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    restart: unless-stopped

  # Development environment with hot reload
  dev:
    image: ghcr.io/cirruslabs/flutter:3.37.0-0.1.pre
    working_dir: /app
    volumes:
      - ..:/app
    network_mode: "host"
    command: flutter run -d web-server --web-hostname=0.0.0.0 --web-port=9001
    profiles:
      - dev
