id: "chat-bot"
agent:
  system_prompt: "./prompt.txt"
  model_name: "qwen3:latest"
tools:
  - tool_name: "soliplex.tools.get_current_datetime"
# - tool_name: "<yourapp>.tools.search_documents"
#     search_path: "/path/to/documents"
