id: "mcptest"
name: "MCP Test"
description: "Test MCP tool interaction."
suggestions:
- "What is the weather in <your location>?"

agent:
  system_prompt: "./prompt.txt"

tools:
  - tool_name: "soliplex.tools.get_current_datetime"

mcp_client_toolsets:

  smithery_nws:
    type: "http"
    url: "https://server.smithery.ai/@smithery-ai/national-weather-service/mcp"
    allowed_tools:
    - "get_current_weather"

    query_params:
      # This is bog stupid:  the SmitheryAI endpoint does not support
      # passing an 'Authorization: Bearer <API KEY>' header, but instead
      # expects to have the values passed in the query string (unless the
      # client can do the full OAuth2 flow).
      api_key: "env:{SMITHERY_AI_API_KEY}"
      profile: "env:{SMITHERY_AI_PROFILE}"

# google_maps:
#   type: "stdio"
#   command: "npx"
#   args: 
#     - "-y"
#     - "@modelcontextprotocol/server-google-maps"
#   env: 
#     GOOGLE_MAPS_API_KEY: GOOGLE_MAPS_API_KEY
