name: Run soliplex unit tests / linting

on:
  push:
    branches:
      - main
    paths:
      - 'soliplex/**'
      - 'tests/**'
      - '.github/workflows/soliplex.yaml'
      - 'uv.lock'
  pull_request:
    branches:
      - main
    paths:
      - 'soliplex/**'
      - 'tests/**'
      - '.github/workflows/soliplex.yaml'
      - 'uv.lock'
  workflow_dispatch:

jobs:
  test-soliplex:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    env:
      BRANCH: "${{ github.head_ref }}"
      RUN_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      COMMIT_MSG: "${{ github.event.head_commit.message }}"
      SLACK_NOTIFY_URL: "${{ secrets.SLACK_NOTIFY_URL }}"
      ENFOLD_GH_PAT: "${{ secrets.ENFOLD_GH_PAT }}"
      ENFOLD_GH_USER: "${{ secrets.ENFOLD_GH_USER }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "**/pyproject.toml"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          #
          # Install 'docling' first using the "CPU-only" index:
          # avoids installing the huge NVidia / CUDA deps we won't use.
          #
          pip install docling \
            --extra-index-url https://download.pytorch.org/whl/cpu
          pip install -e . --group dev
      - name: Run soliplex unit tests
        run: |
          pip list
          py.test
      - name: Run ruff linter
        run: |
          ruff check
      - name: Notify Slack on failure
        if: failure()
        run: |
          curl -X POST \
            --data-urlencode \
            "payload={\"channel\": \"#soliplex\", \"username\": \"soliplex\", \"text\": \":x: $GITHUB_WORKFLOW failed on $BRANCH:\n$COMMIT_MSG\n$RUN_URL\", \"icon_emoji\": \":ghost:\"}" \
            "$SLACK_NOTIFY_URL"
