id: "haiku"
name: "Haiku-RAG search"
description: "Search documents using Haiku-RAG"
suggestions:
- "Which way is up?"
agent:
  system_prompt: "./prompt.txt"
allow_mcp: true
tools:
  - tool_name: "soliplex.tools.get_current_datetime"
    allow_mcp: true
  - tool_name: "soliplex.tools.search_documents"
    rag_lancedb_override_path: "../../../db/rag/rag.lancedb"
    return_citations: true
    expand_context_radius: 3
    search_documents_limit: 7
    allow_mcp: true
# - tool_name: "<yourapp>.tools.get_current_user"
